### ISSUE TITLE
터미널 로그인 오류

### ISSUE THREAD

**Issue by SoonchanGwon** [keris2020/hackathon#10]
![image](https://user-images.githubusercontent.com/65800027/97866082-920e5700-1d4e-11eb-891f-a3db78139836.png)

그림과 같이 로그인이 안됩니다. 
당연히 지금 깃허브에는 정상적으로 로그인 된 상태로 글을 쓰는 것이니까.
비밀번호를 잊은 것은 아니구요..

게다가 웹브라우저는 로그인이 됩니다.

![image](https://user-images.githubusercontent.com/65800027/97866331-195bca80-1d4f-11eb-8f78-d85ad6de1269.png)

**Comment by Jun-Pyo-Park-PhD** [comment]
동일 증상이 발견되어 현재 확인 중입니다. 처리 완료 후 다시 답글을 달아드리도록 하겠습니다.

**Comment by Jun-Pyo-Park-PhD** [comment]
현재 정상화되었습니다. 불편을 드려 죄송합니다.
