### ISSUE TITLE
local-nsml 설치 오류

### ISSUE THREAD

**Issue by vega71** [keris2020/hackathon#11]
cmd창에서 pip install git+https://github.com/n-CLAIR/nsml-local 라고 치면 아래와 같은 에러가 납니다.

Collecting git+https://github.com/n-CLAIR/nsml-local
  Cloning https://github.com/n-CLAIR/nsml-local to c:\users\user\appdata\local\temp\pip-req-build-li49gvy8
  ERROR: Error [WinError 2] 지정된 파일을 찾을 수 없습니다 while executing command git clone -q https://github.com/n-CLAIR/nsml-local 'C:\Users\user\AppData\Local\Temp\pip-req-build-li49gvy8'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by taeseug** [comment]
위의 에러는 git 가 설치 되어 있지 않거나 경로설정에 들어 있지 않아 발생하는 에러입니다. 
아래 링크를 참조하세요
https://github.com/keris2020/hackathon/issues/12#issuecomment-720552340

**Comment by taeseug** [comment]
git프로그램이 설치 되어 있지 않아서  발생하는 에러인것 같습니다. 
아래 링크를 첨조하세요
https://github.com/keris2020/hackathon/issues/12#issuecomment-720552340

conda install git
git clone https://github.com/n-CLAIR/nsml-local.git
cd nsml-local
python3 setup.py install
