### ISSUE TITLE
tensorflow 오류

### ISSUE THREAD

**Issue by segolni** [keris2020/hackathon#13]
![image](https://user-images.githubusercontent.com/21963688/97877866-284b7880-1d61-11eb-902f-d5ba009a097e.png)
nsml상의 tensorflow가 버전이 낮아 다음과 같은 오류가 떠 tf.random.set_seed가 아니라 tf.set_random_seed를 사용해야합니다 버전업그레이드를 할 수 있나요?

**Comment by bluebrush** [comment]
@segolni 님.

`requirements.txt` 또는 `setup.py` 파일의 맨 윗줄에 아래와 같이 적으시면 다른 docker image를 사용할 수 있습니다. 

```
#nsml: nvcr.io/nvidia/tensorflow:20.06-tf2-py3
```
[setup.py] 참고, 
https://github.com/imcomking/AI_Starthon_2019/blob/6cc039c8e0ef504c90000dd8fe7835c813ab51c5/16_tcls_movie/setup.py#L1


아래 링크에서 nsml에 cache되어있는 docker를 확인하시고 빠르게 활용하실 수 있습니다. 
https://ai.nsml.navercorp.com/support

**Comment by okgosu** [comment]
추가적으로, 

python 코드 내에서 NSML에서 실행인지, PC에서 실행인지에 따라 구분하는 방법도 있습니다. 

import tensorflow as tf
from nsml import IS_ON_NSML

```
if IS_ON_NSML:
    # NSML에서 실행
    tf.set_random_seed(3)
else:
   # 로컬 PC에서 실행
   tf.random.set_seed(3)
```
