### ISSUE TITLE
Hello test조차 실행방법을 모르겠어요

### ISSUE THREAD

**Issue by vega71** [keris2020/hackathon#14]
print("Hello NSML")을 main.py로 저장하여
nsml run -e main.py로 실행했을 때 오류가 납니다.

![image](https://user-images.githubusercontent.com/73425194/97949923-73ed3900-1dd8-11eb-8738-5586330be18a.png)

**Comment by okgosu** [comment]
질문 2가지 드립니다.
1) main.py가 있는 폴더 이름이 어떻게 되나요? 
2) C:\Users\User 폴더에 들어 있는 파일 목록이 어떻게 되나요?

**Comment by taeseug** [comment]
hello_nsml 테스트 파일 입니다. 다운받으셔서 참고하세요
아래 파일 다운 받으신 후  압축풀으신후 실행 시켜 보세요  압축풀어서 보시면 이해가 더 쉽게 되실 수 있습니다.
1. nsml login
2. nsml run -d hello_nsml     <= hello_nsml은 nsml 에 올라가 있는 dataset 입니다.  
                                                   압축파일을 열어 보시면 /dataset 디렉토리에 있는 파일을 NSML 에 미리 올려 놓은 것입니다.

참고로 dataset 확인을 위해서는   'nsml dataset ls' 하시면 보실 수 있습니다,

[hello_nsml.zip](https://github.com/keris2020/hackathon/files/5479434/hello_nsml.zip)

**Comment by okgosu** [comment]
오류가 나는 원인은 아래와 같습니다.
- NSML을 run 하면 실행하는 폴더에 있는 파일들을 읽어들여 NSML 서버로 전송하는데요,
- 에러 메시지를 보면  C:\Users\User 폴더에 .conda/environments.txt 파일에 '.'이 포함되어 있어 문제가 있다는 것입니다. 

해결책은 아래와 같습니다.
 C:\Users\User 폴더에 새로운 폴더를 만드시고, 여기에 main.py를 넣어서 실행하시길 바랍니다. 
굳이  C:\Users\User  폴더에서 실행을 원하시면,  .nsmlignore 파일을 만드시고, 거기 맨 윗줄에 .conda/environments.txt  를 넣으시면 됩니다.

**Comment by ghost** [comment]
저도 같은 증상의 오류가 났는데요, 걱정되는 마음에 혹시나 해서 질문드립니다.
(파일은 C:nsml 폴더에 저장합니다)

 1. 사진에서는 ".conda\\environments.txt" 에서 역슬래시가 2개 있는데, 고수님은 슬래시 1개를 넣으셔서 무엇이 맞는지 궁금합니다.
2. 저는 ".vscode\\settings.json"이 문제라고 뜨는데, 그러면 메모장에 붙여넣기 한 뒤, 제목을 .nsmlignore이라고 지으면 될까요?
