### ISSUE TITLE
터미널 로그인 오류

### ISSUE THREAD

**Issue by Jeonseungjae** [keris2020/hackathon#15]
제 친구 pc에서 다른 컴퓨터에서는 잘 로그인 되는 계정들도 계속 인증 오류가 납니다. 고칠 수 있는 방법이 있을까요?

**Comment by taeseug** [comment]
방화벽이 실해될수 있으니 이 부분 확인해 보세요

**Comment by Jun-Pyo-Park-PhD** [comment]
아래와 같이 에러메시지가 출력되면 방화벽 문제이니, 방화벽을 해제하신 후 로그인해보시기 바랍니다.

![image](https://user-images.githubusercontent.com/70569284/97955118-c9314680-1de8-11eb-9028-ae1ecab78dc5.png)
