### ISSUE TITLE
dataset에 보이는 파일

### ISSUE THREAD

**Issue by shxxrim** [keris2020/hackathon#16]
nsml run으로 실행시킨 파일이 session에는 보이는데, 혹시 dataset의 file system에도 보여야 하는 것 아닌가요??

**Comment by okgosu** [comment]
nsml run 하면, 실행하는 폴더의 파일들(실행파일 포함)을 nsml 클라우드 서버로 모두 전송합니다.
dataset은 서버 정책상 파일시스템에 노출하지 않도록 되어 있습니다...물론 그렇게 해도 되지만 그럴 필요는 없다는 판단입니다.
파일시스템 구조는 DATASET_PATH 변수가 기본 폴더가 되고, 그 하위에 지정된 dataset이 보이도록 되어 있습니다.
중요한 것은 파일의 위치가 아니라,  ai 학습을 하는데 필요한 중요한 정보는 데이터의 structure이며, 이 부분은 데이터 설명문서를 참조하시길 바랍니다.
