### ISSUE TITLE
conda install git도 안 됩니다

### ISSUE THREAD

**Issue by ksy809** [keris2020/hackathon#17]
C:\Users\User>conda install git
'conda'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

처음부터 잘못된 거 일까요???

**Comment by ksy809** [comment]
해결했습니다. 그런데 문제가 생겼습니다. pip가 안 되면 conda 뭐시기를 대신 쓰라고 하셔서 했는데 마지막에 있는 python3 setup.py install 이 친구만 안 됩니다. 저만 그런게 아닙니다. 저희 학교 친구들도 안 됩니다. 빠른 해결 부탁합니다.

**Comment by okgosu** [comment]
conda를 사용하는 이유를 먼저 이해하셔야 합니다.
나중에 python 부터 tensorflow, pytorch 등의 라이브러리를 설치를 하시게 되는데, 이것들이 버전이 서로 다르게 되고, '
필요에 따라 다른 버전의 조합으로 환경을 구성해서 실행할 필요가 생깁니다.
conda를 설치하지 않으면, 버전이 다른 동일한 sw가 있다면 매번 라이브러리를 삭제하고 새로 깔아야 하기 때문입니다.
