### ISSUE TITLE
밑에 댓글 달렸다고 안 보셨을까봐 다시 올립니다.

### ISSUE THREAD

**Issue by ksy809** [keris2020/hackathon#19]
밑에 댓글 내용입니다. 
해결했습니다. 그런데 문제가 생겼습니다. pip가 안 되면 conda 뭐시기를 대신 쓰라고 하셔서 했는데 마지막에 있는 python3 setup.py install 이 친구만 안 됩니다. 저만 그런게 아닙니다. 저희 학교 친구들도 안 됩니다. 빠른 해결 부탁합니다.

**Comment by taeseug** [comment]
python3  setup.py install  실행시 나온 메세지를 올려주세요

**Comment by ksy809** [comment]
(base) C:\Users\User\nsml-local>python3 setup.py instalL
'python3'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

**Comment by hansungg** [comment]
python3 대신에 python으로 실행시켜보세요
가끔 python 실행파일이 python3 대신에 python 으로 되어있는 경우가 있습니다. 

ex) python setup.py install
