### ISSUE TITLE
데이터셋확인이 안됩니다

### ISSUE THREAD

**Issue by nayeon902** [keris2020/hackathon#22]
데이터셋을 확인하려고 nsml dataset Is를 입력했는데 올라와있는 데이터들이 하나도 안뜹니다.
명령 프롬프트에서 진행하는게 맞는건가요??

**Comment by taeseug** [comment]
' nsml dataset ls' 은 명령 프롬프트에서 실행 시키는게 맞습니다,  하지만 그전에  'nsml login' 을 통해 nsml 에 로그인을 해야 합니다. 그래야  데이터셋 정보가 보입니다. 이 보입니다.  좀더 자세한 원인 파악을 위해서는 에러로그를 올려 주세요

(base) C:\Users\MSI>nsml login
time="2020/11/04 06:35:59.139" level=info msg="connecting to ai-cli.nsml.navercorp.com:443"
GitHub Username: github_id
GitHub Password: ***********
time="2020/11/04 06:36:09.534" level=info msg="Welcome to NSML!"

(base) C:\Users\MSI>nsml dataset ls
Name                 Size       Last Modified    Author       Description    Tag    Authority
-------------------  ---------  ---------------  -----------  -------------  -----  -----------
16_tcls_movie        993.61 MB  11 days ago      keris_admin                        public
16_tcls_movie_small  99.95 MB   2 days ago       keris_admin                        public
2020KHD_PNS          176.48 MB  a month ago      khdadmin                           private
Breast_Pathology     4.94 GB    a month ago      khdadmin                           private
PNS5                 1.76 MB    a month ago      khdadmin                           private
Sample               117.54 KB  2 months ago     khdadmin                           private
fashion_dataset      2.32 GB    a month ago      kaist-00                           private

**Comment by okgosu** [comment]
데이터셋 목록은 여기서도 확인 가능합니다.

https://ai.nsml.navercorp.com/datasets
