### ISSUE TITLE
주피터 노트북 import keras, tensorflow 에러

### ISSUE THREAD

**Issue by ndh6592** [keris2020/hackathon#25]
에러메시지..

![캡처](https://user-images.githubusercontent.com/73160978/98066781-58973200-1e9b-11eb-845f-ac1d46192aa9.PNG)

**Comment by taeseug** [comment]
anaconda를 사용하고 계시면  pip 보다 conda install tensorflow 해 주시는게 좋습니다

**Comment by ndh6592** [comment]
conda install tensorflow로 했는데 저렇게 됩니다
