### ISSUE TITLE
선생님 급합니다. 빨리와서 해결 좀 해주세요 jupyter notebook 문제입니다.

### ISSUE THREAD

**Issue by ksy809** [keris2020/hackathon#26]
import keras를 하면 결과로
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-88d96843a926> in <module>
----> 1 import keras

ModuleNotFoundError: No module named 'keras'
 이렇게 뜹니다. 뭐가 문제일까요??
아래 질문에 있는 답처럼 uninstall해서 다시 다운도 받았습니다. 그런데도 문제가 있다네요 빠른 해결 바랍니다.

**Comment by taeseug** [comment]
이 에러는 keras 모듈이 설치가 안되서 나오는 에러입니다. 
import keras 로 사용하는 방법은 tensorflow 1.0 버젼에서 주로 사용하던 방식입니다. 
tensorflow 1.0 버젼에서는 keras  module 과 따로 사용하였기 때문에 import  keras를 사용하였습니다.
tensorflow 2.0 이후 부터는  keras가  tensorflow에 포함 되어 있어 따로 설치가 필요 없습니다, 

두버젼의 차이는 

지금 사용하시는 tensorflow가 2.0 버젼 이상이시면 
from tensorflow.keras.datasets import mnist 하시면 됩니다. 

tensorflow 1.0 version 쓰시며 keras 를 사용하실 경우   
 from keras.datasets import  mnist 

입니다. 


첨부로  tensorflow 2.0 버전으로 변형한 jupyter notebook 올려 드립니다 참조하세요

[MNIST실습.zip](https://github.com/keris2020/hackathon/files/5485491/MNIST.zip)

**Comment by ksy809** [comment]
그러면 선생님
ModuleNotFoundError                       Traceback (most recent call last)
~\anaconda3\lib\site-packages\keras\__init__.py in <module>
      2 try:
----> 3     from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
      4 except ImportError:

~\anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader

ModuleNotFoundError: No module named 'tensorflow.python'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-88d96843a926> in <module>
----> 1 import keras

~\anaconda3\lib\site-packages\keras\__init__.py in <module>
      3     from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
      4 except ImportError:
----> 5     raise ImportError(
      6         'Keras requires TensorFlow 2.2 or higher. '
      7         'Install TensorFlow via `pip install tensorflow`')

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

이렇게 뜨면 아나콘다에 pip install tnesorflow를 입력해야 하나요?????????

**Comment by taeseug** [comment]
anaconda 에서는 pip 보다는 conda install tensorflow 를 사용하시는 것이 좋습니다, 

conda 를 사용하실 경우에는 관련 package들의 version호환성을 고려 하여 설치해 주기 때문입니다,
