### ISSUE TITLE
adamp 오류

### ISSUE THREAD

**Issue by southriver119** [keris2020/hackathon#27]
![image](https://user-images.githubusercontent.com/73562983/98067878-e4aa5900-1e9d-11eb-9a67-733b95b53c69.png)

**Comment by taeseug** [comment]
adamp  package가 설치 안되서 나는 에러 같습니다. 

먼저
         pip install adamp 하시고 실행 시켜 주세요

**Comment by southriver119** [comment]
로컬 PC에서가 아니라 NSML 플랫폼에서 나는 에러입니다.

**Comment by taeseug** [comment]
nsml  실행시 관련 package를 setup.py에 넣어서 설치 해 주어야 실행 됩니다. 

setup(
    name='iitp_trash',
    version='1.0',
    install_requires=[
                              'adamp'
                              ]
)

좀더 자세한 사항은 아래 링크를 참조하세요  
https://github.com/clovaai/adamp
