### ISSUE TITLE
nsml run 오류

### ISSUE THREAD

**Issue by southriver119** [keris2020/hackathon#28]
submit을 한번 하고 난 이후로 다시 run을 했을 때 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/73562983/98077879-59888d80-1eb4-11eb-89f1-fdce1a1fd7ab.png)

**Comment by taeseug** [comment]
로그상에는 별다른 메세지가 안나옵니다.  다시한번더 실행 해 주세요

**Comment by southriver119** [comment]
> 로그상에는 별다른 메세지가 안나옵니다. 다시한번더 실행 해 주세요

계속 똑같은 에러가 발생합니다.. 실행번호가 20이 넘었습니다. ㅠㅠ
