### ISSUE TITLE
선생님 제발 쉬운 말로 도와주십시오

### ISSUE THREAD

**Issue by ksy809** [keris2020/hackathon#30]
jupyter notebook에 import keras를 입력했습니다. 
그 결과로
ImportError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     63   try:
---> 64     from tensorflow.python._pywrap_tensorflow_internal import *
     65   # This try catch logic is because there is no bazel equivalent for py_extension.

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 지정된 모듈을 찾을 수 없습니다.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
      2 try:
----> 3     from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
      4 except ImportError:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     39 
---> 40 from tensorflow.python.eager import context
     41 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py in <module>
     34 from tensorflow.core.protobuf import rewriter_config_pb2
---> 35 from tensorflow.python import pywrap_tfe
     36 from tensorflow.python import tf2

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py in <module>
     27 # pylint: disable=invalid-import-order,g-bad-import-order, wildcard-import, unused-import
---> 28 from tensorflow.python import pywrap_tensorflow
     29 from tensorflow.python._pywrap_tfe import *

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     82 above this error message when asking for help.""" % traceback.format_exc()
---> 83   raise ImportError(msg)
     84 

ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 지정된 모듈을 찾을 수 없습니다.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-5-88d96843a926> in <module>
----> 1 import keras

C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
      3     from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
      4 except ImportError:
----> 5     raise ImportError(
      6         'Keras requires TensorFlow 2.2 or higher. '
      7         'Install TensorFlow via `pip install tensorflow`')

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
이렇게 뜹니다.
여기서 제가 듣고 싶은 말은 다른 방법을 알려달라는 것이 아니라 뭐가 문제인지 그리고 그것에 대한 해결 방안을 알고 싶습니다. 
간결한 설명이 아닌 정말 자세한 해결 방안 부탁드립니다.

**Comment by kdh7979** [comment]
저도 그 오류가 떠서 찾아보니
https://needneo.tistory.com/47
위 사이트대로 하니 해결됐습니다.

**Comment by ksy809** [comment]
알려주셔서 감사합니다. 허나 제 컴퓨터와 제 친구 컴퓨터로는 되지 않습니다. 다른 방법은 없나요??

**Comment by ksy809** [comment]
ModuleNotFoundError                       Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
      2 try:
----> 3     from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
      4 except ImportError:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     39 
---> 40 from tensorflow.python.eager import context
     41 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py in <module>
     38 from tensorflow.python.eager import executor
---> 39 from tensorflow.python.eager import monitoring
     40 from tensorflow.python.framework import c_api_util

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\monitoring.py in <module>
     27 from tensorflow.python.client import pywrap_tf_session
---> 28 from tensorflow.python.framework import c_api_util
     29 from tensorflow.python.util import compat

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\c_api_util.py in <module>
     24 from tensorflow.python.client import pywrap_tf_session as c_api
---> 25 from tensorflow.python.util import compat
     26 from tensorflow.python.util import tf_contextlib

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\compat.py in <module>
     54 
---> 55 from tensorflow.python.util.tf_export import tf_export
     56 

ModuleNotFoundError: No module named 'tensorflow.python.util.tf_export'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-5-88d96843a926> in <module>
----> 1 import keras

C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
      3     from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
      4 except ImportError:
----> 5     raise ImportError(
      6         'Keras requires TensorFlow 2.2 or higher. '
      7         'Install TensorFlow via `pip install tensorflow`')

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

이렇게 뜹니다. 도와주세요 ㅜㅜㅜ
