### ISSUE TITLE
진짜 빨리 답 좀 해주세요 급해요

### ISSUE THREAD

**Issue by ksy809** [keris2020/hackathon#31]
https://needneo.tistory.com/47

이 사이트대로 하라고 해서 했는데도 불구하고 
ModuleNotFoundError Traceback (most recent call last)
 C:\ProgramData\Anaconda3\lib\site-packages\keras_init_.py in 
 2 try:
 ----> 3 from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
 4 except ImportError:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_init_.py in 
 40
 ---> 41 from tensorflow.python.tools import module_util as _module_util
 42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python_init_.py in 
 39
 ---> 40 from tensorflow.python.eager import context
 41

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py in 
 38 from tensorflow.python.eager import executor
 ---> 39 from tensorflow.python.eager import monitoring
 40 from tensorflow.python.framework import c_api_util

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\monitoring.py in 
 27 from tensorflow.python.client import pywrap_tf_session
 ---> 28 from tensorflow.python.framework import c_api_util
 29 from tensorflow.python.util import compat

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\c_api_util.py in 
 24 from tensorflow.python.client import pywrap_tf_session as c_api
 ---> 25 from tensorflow.python.util import compat
 26 from tensorflow.python.util import tf_contextlib

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\compat.py in 
 54
 ---> 55 from tensorflow.python.util.tf_export import tf_export
 56

ModuleNotFoundError: No module named 'tensorflow.python.util.tf_export'

During handling of the above exception, another exception occurred:

ImportError Traceback (most recent call last)
in 
 ----> 1 import keras

C:\ProgramData\Anaconda3\lib\site-packages\keras_init_.py in 
 3 from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
 4 except ImportError:
 ----> 5 raise ImportError(
 6 'Keras requires TensorFlow 2.2 or higher. '
 7 'Install TensorFlow via pip install tensorflow')

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via pip install tensorflow

이렇게 뜹니다. 도와주세요 ㅜㅜㅜ

**Comment by kjn6318** [comment]
Failed to load ~~~~~ runtime 오류
==> 64비트 운영체제라면 x86(32비트) x64 모두 설치해주세요.
https://support.microsoft.com/ko-kr/help/2977003/the-latest-supported-visual-c-downloads

파이썬 버전 문제인 경우 No module named 오류
==> PC에 이미 파이썬이 설치되어 있는 경우 아나콘다 설치 시 오류가 나는 경우가 있습니다. 파이썬을 지우고 다시 처음부터 다시 설치해주시면 대부분 해결됩니다.

* PC 재기동 

NSML 이용 및 설정 등은 다음 문서를 참조해주세요. 
http://gg.gg/mapo_ai_doc

**Comment by okgosu** [comment]
원인) keras를 사용하기 위해 필요한  TensorFlow 의 버전이 2.2 이전 버전인 듯 하네요.
로그를 보시면 keras는 TensorFlow 2.2 이상을 지원한다고 되어 있어요. 

해결책) 
아나콘다를 통해서 TensorFlow와 Keras 버전을 맞춰줘야 하는데요.
아래 내용을 보시고 따라해보세요.
https://devpad.tistory.com/39
