### ISSUE TITLE
import keras 다른 해결방법으로도 계속 에러가 떠요 

### ISSUE THREAD

**Issue by eun4204** [keris2020/hackathon#32]
![image](https://user-images.githubusercontent.com/73326251/98083716-1d5a2a80-1ebe-11eb-9fdf-30f22e00a3d1.png)

conda install tensorflow 도 설치해봤고 새글에 올라온  방법으로 비주얼 무슨 프로그램 설치해서 다시시작 하는것도 해봤는데 계속 저렇게 뜹니다 ㅠㅠㅠㅠ 도대체 뭐가 문제인가요? 아예 다시 시작하는게 좋을까요...

**Comment by kjn6318** [comment]
파이썬 버전 문제인 경우 No module named 오류
==> PC에 이미 파이썬이 설치되어 있는 경우 아나콘다 설치 시 오류가 나는 경우가 있습니다. 파이썬을 지우고 다시 처음부터 다시 설치해주시면 대부분 해결됩니다.

PC 재기동
NSML 이용 및 설정 등은 다음 문서를 참조해주세요.
http://gg.gg/mapo_ai_doc

**Comment by kjn6318** [comment]
네이버 안내를 공유드립니다.

원인) keras를 사용하기 위해 필요한 TensorFlow 의 버전이 2.2 이전 버전인 듯 하네요.
로그를 보시면 keras는 TensorFlow 2.2 이상을 지원한다고 되어 있어요.

해결책)
아나콘다를 통해서 TensorFlow와 Keras 버전을 맞춰줘야 하는데요.
아래 내용을 보시고 따라해보세요.
https://devpad.tistory.com/39

**Comment by taeseug** [comment]
jupyter notebook 에서 import tensorflow은 작동하나요 만일 정상적으로 작동되면 아래 jupyter notebook 파일을 잃어 실행 시켜 보세요
그리고 tensorflow version 1.0 -> 2,0으로 업그레이드 되면서 기존 keras package가 tensorflow package와 합쳐졌습니다.
텐서플로버젼확인은 
import tensorflow as tf;print(tf.__version__)  넣고 실행시켜보세요

[MNIST실습.zip](https://github.com/keris2020/hackathon/files/5486448/MNIST.zip)
