### ISSUE TITLE
영화 평점 예측 baseline 코드 질문 입니다.

### ISSUE THREAD

**Issue by Jeonseungjae** [keris2020/hackathon#33]
regression 과 classification 함수가 models.py 코드 안에 같이 존재하는 것을 알았습니다.(그리고 두 함수의 내용은 매우 비슷했습니다.) 이때 main.py 안에서 regression 에는 MSE 손실 함수가 쓰였고, classification 에는 crossentropy 손실함수가 쓰인걸 보았습니다. 영화의 평점을 예측하는것에 왜 두가지의 손실함수가 모두 쓰였는지 이유가 궁금합니다.

**Comment by Jeonseungjae** [comment]
아 그리고 또 영화 평점을 예측하는것에 MSEloss 함수 사용또한 의문이 듭니다.

**Comment by okgosu** [comment]
네, 질문 확인했고, 내부 ai 연구원들 답변 내용 준비되는대로 답변드릴게요.

**Comment by gyuwankim** [comment]
안녕하세요
주어진 테스크는 영화 리뷰가 주어졌을때 0에서 10 사이의 정수로 표현 되는 영화 평점을 반환 하는 문제입니다.
이를 위해 먼저 regression 문제로 접근해서 실수 값으로 점수를 표현하고 그에 가장까운 정수를 반환하는 방식으로도 풀 수 있고
또는 0, 1, ..., 10 사이의 가능한 11개의 정수 값 중 하나로 분류하는 classifcation 문제로 풀수도 있습니다.
Regression 문제의 경우는 예측 점수와 실제 점수의 차이를 최소화하도록 MSE loss로 학습을 하고 Classification의 경우에는 모델이 각 클래스에 대한 확률 값을 예측하기 때문에 정답의 확률을 최대화 해주는 Cross entropy loss로 학습을 합니다.
