### ISSUE TITLE
nsml run이 작동이안됩니다

### ISSUE THREAD

**Issue by nayeon902** [keris2020/hackathon#36]
nsml run -d mnist3 -e main.py 가 작동이 안됩니다. 
dir 입력해보니 main.py파일이 없는데 이 파일은 어디에 만들어야되는건가요?

**Comment by okgosu** [comment]
아무 폴더에 넣으시되, 명령어는 그 폴더에서 실행하시면 됩니다.

c:/aaa/main.py를 만들었다면,

nsml run 명령어는 c:/aaa 폴더에서 실행하면 됩니다.

**Comment by nayeon902** [comment]
c:_aaa폴더에서 실행한다는게 nsml run 뒤에 실행파일에 써라는건가요??

**Comment by Jun-Pyo-Park-PhD** [comment]
김나연 학생, 
위의 c:\aaa 폴더는 예를 드신거구요.


nsml run 은 항상 **실행할 파일이 있는 경로로 먼저 이동한 후** 실행해야 합니다. 

예제 1)
예를 들어, 만약 **c:\nsml** 폴더에 main.py 파일이 있으면
![image](https://user-images.githubusercontent.com/70569284/98122848-793fa600-1ef4-11eb-9452-e7a02673b675.png)

이런 식으로 커맨드창에서 mnist 를 실습할 main.py 파일이 있는 경로(여기서는 **c:\nsml**)로 먼저 이동하시고
 (커맨드창 명령어 _cd c:\nsml_) 
nsml run -d mnist3 -e main.py 를 실행하시고


예제 2)
c:\nsml\mnist 폴더에 main.py 파일이 있으면 
![image](https://user-images.githubusercontent.com/70569284/98123120-cf144e00-1ef4-11eb-9ed3-a6faf070b769.png)

위와 같이 **c:\nsml\mnist** 폴더로 이동하신 후 (커맨드창 명령어 _cd c:\nsml\mnist_)
 _nsml run -d mnist3 -e main.py_ 명령어를 실행하면 됩니다.


현재 nsml 을 실행할 커맨드 창 경로가 실행할 파일이 있는 경로와 일치하는지 꼭 확인하세요!
