### ISSUE TITLE
컴퓨터 포멧후 안됨

### ISSUE THREAD

**Issue by wlsdnr2314** [keris2020/hackathon#38]
컴퓨터 포멧 이후 다시 모든것을 설치하고 왔습니다. 관리자 계정으로 놋북이 로그인이 안되어서 main.py를 바탕화면에 폴더를 만들어 넣어놓았습니다. 그리고 현재 쥬피터 안에 import keras 부터 print('Hello NSML')까지 작성한 get-pip.py라는 py파일을 바탕화면에 놓았습니다 이 이후 nsml run -e get-pip.py를 하면 도중에 멈추고 정상 작동하지 않습ㄴ다.
![캡처](https://user-images.githubusercontent.com/73600659/98152608-57a2e680-1f15-11eb-9323-7855283ade72.PNG)

**Comment by wlsdnr2314** [comment]
해결했습니다

**Comment by okgosu** [comment]
nsml 을 실행하려는 파이썬 코드가 있는 폴더에는 이름이 .으로 시작되는 파일이 있으면 안됩니다.
참고) https://github.com/keris2020/hackathon/issues/14

**Comment by okgosu** [comment]
@wlsdnr2314 다른 분들을 위해 어떻게 해결하셨는지 내용 간략히 답변 해주시면 도움될거 같아요.
