### ISSUE TITLE
nsml run에서  setup.py 오류

### ISSUE THREAD

**Issue by shxxrim** [keris2020/hackathon#40]
AdamP를 사용하려고  setup을 수정하여 run을 실행하니 다음과 같은 에러가 납니다.

![image](https://user-images.githubusercontent.com/66543110/98187441-475e2c00-1f54-11eb-9be4-15e6b35173a8.png)

**Comment by taeseug** [comment]
setup.py 파일 내용을 올려 주실 수있나요

**Comment by shxxrim** [comment]
![image](https://user-images.githubusercontent.com/66543110/98189409-44fdd100-1f58-11eb-8ca1-5187ebfa17e5.png)

**Comment by okgosu** [comment]
명령어가 잘못되었어요.
X) nsml run -d 16_tcls_movie_small -e setup.py
O) nsml run -d 16_tcls_movie_small -e main.py
(main.py는 작성하셨겠죠?)

**Comment by taeseug** [comment]
nsml 실행시 관련 package를 setup.py의 install requires 에 넣어서 설치 해 주어야 실행 됩니다.
 
setup(
name='nsml movie review',
version='1.0',
install_requires=[
'adamp'                                < == 이렇게 넣어 주세요
]
)

좀더 자세한 사항은 아래 링크를 참조하세요
https://github.com/clovaai/adamp
