### ISSUE TITLE
hello 데이터셋 코딩

### ISSUE THREAD

**Issue by binwon06** [keris2020/hackathon#41]
주피터에서는 train/data.txt가 없으므로 같은 폴더에 생성하란느데 여기서 같은 폴더는 무슨 폴더를 말하는 것이고
train/data.txt는 어디서 얻는건가요?

**Comment by okgosu** [comment]
main.py라는 파일이 있는 폴더에 train 폴더 만드시고, 거기에 data.txt라는 이름으로 파일을 만드셔서, 아무 내용이나 몇줄 넣어 놓으시면 됩니다. 
예를 들어, c:\user 라는 폴더에 main.py를 만드셨다면, data.txt는 c:\user\train\data.txt 를 만들어 놓으시면 됩니다. 

정리하자면, c:\user라는 곳에서 작업한다고 가정할게요. 
1단계) c:\user 폴더로 이동
2단계) c:\user 폴더에 train 폴더 생성  
3단계) c:\user\train 폴더에 data.txt 생성 (내용은  hello nsml 등등....텍스트 몇 줄 넣어 놓으면 됩니다.)
4단계)  c:\user 폴더에 main.py 작성 
```
import os
from nsml import GPU_NUM, DATASET_PATH, DATASET_NAME  
with open(os.path.join(DATASET_PATH, 'train/data.txt')) as f:
     print('read from dataset {0}'.format(DATASET_NAME), [line for line in f])
```

5단계) c:\user 폴더에서 아래 명령어 실행
nsml run -d hello -e main.py 

<참고> 'hello'라는 dataset은 nsml에 아래에 등록이 되어 있어서 사용가능합니다.
- https://ai.nsml.navercorp.com/filesystem/hello

<전체 파일 구조 예시>
 c:\user\main.py
 c:\user\train\data.txt
