### ISSUE TITLE
세션 실행결과 확인

### ISSUE THREAD

**Issue by binwon06** [keris2020/hackathon#42]
![캡처](https://user-images.githubusercontent.com/73326204/98194654-379a1400-1f63-11eb-91d6-1a0c75a41b3b.PNG)

nsml에 들어가서 세션 확인했는데 이렇게 뜨는데요 세션은 존재하는데 위에 부분이 오류가 난 것 같아서
어디에서 잘못된건지 질문드립니다. 주피터노트북에서 keras torch nsml 다 오류 안나고 잘 됐고 아나콘다 프롬포트에서 run해서 실행시켰을때도 세션명 뜨고 잘 됐습니다

**Comment by okgosu** [comment]
true가 아니라 True 아닐까요?

**Comment by binwon06** [comment]
그걸 어떻게 수정하는거죠ㅜㅜ??
