### ISSUE TITLE
학습을 했다고 생각하고 학습완료된 모델 목록을 확인했습니다

### ISSUE THREAD

**Issue by seoin0402** [keris2020/hackathon#43]
근데 체크포인트에 학습완료된 모델 목록에 아무것도 뜨지 않습니다

(base) C:\nsml>nsml model ls KERIS019/16_tcls_movie_small/9
Checkpoint    Last Modified    Elapsed    Summary    Size
------------  ---------------  ---------  ---------  ------

(base) C:\nsml>nsml model ls KERIS019
time="2020/11/05 12:37:24.429" level=fatal msg="invalid argument: KERIS019"

(base) C:\nsml>nsml model ls KERIS019/16_tcls_movie_small/9
Checkpoint    Last Modified    Elapsed    Summary    Size
------------  ---------------  ---------  ---------  ------

(base) C:\nsml>nsml run -d 16_tcls_movie_small -e main.py
time="2020/11/05 12:38:35.580" level=info msg=".nsmlignore check - start"
time="2020/11/05 12:38:35.600" level=info msg=".nsmlignore check - done"
time="2020/11/05 12:38:35.674" level=info msg="file integrity check - start"
time="2020/11/05 12:38:35.682" level=info msg="file integrity check - done"
time="2020/11/05 12:38:35.688" level=info msg="main.py 1.5 KiB - start"
time="2020/11/05 12:38:35.695" level=info msg="main.py 1.5 KiB - done (1/1 100.00%) (1.5 KiB/1.5 KiB 100.00%)"
...Use the default image (nsml/default_ml:latest) because format does not match or you did not set the docker image in advance.
...
Building docker image. It may take a while
.......
Session KERIS019/16_tcls_movie_small/10 is started

**Comment by seoin0402** [comment]
학습을 하고 목록을 보려면 어떻게 해야하나요? 가이드대로 했는데 목록이 안나옵니다~

**Comment by okgosu** [comment]
nsml model ls KERIS019/16_tcls_movie_small/10

(KERIS019/16_tcls_movie_small/10 --> 이것이 세션이름입니다.)

http://gg.gg/mapo_ai_doc 가이드의 4.4 참조하세요.
