### ISSUE TITLE
conda install tensorflow 설치 failed 

### ISSUE THREAD

**Issue by eun4204** [keris2020/hackathon#44]
![image](https://user-images.githubusercontent.com/73326251/98195868-1be43d00-1f66-11eb-9260-c285482be6a4.png)

conda install tensorflow 로 실행하면 계속 failed 가 뜹니다 이거 때문에 주피터에서 import keras 하면 오류가 뜨는 것 같아요 ㅠㅠ 뭐가 문제인가요

**Comment by Jun-Pyo-Park-PhD** [comment]
pip install tensorflow 로 한번 시도해 보세요 :)

**Comment by eun4204** [comment]
그것도 안되는데요 ㅠㅠ !!!!

**Comment by Jun-Pyo-Park-PhD** [comment]
@eun4204 
conda -V 명령어 입력해서 버전 한번 보여주실래요?

**Comment by eun4204** [comment]
(base) C:\Users\User>conda -V
conda 4.8.3

이렇게 뜹니다 !

**Comment by eun4204** [comment]
(base) C:\Users\User>pip install tensorflow
Collecting tensorflow
  Using cached tensorflow-2.3.1-cp38-cp38-win_amd64.whl (342.5 MB)
Collecting protobuf>=3.9.2
  Using cached protobuf-3.13.0-py2.py3-none-any.whl (438 kB)
Collecting keras-preprocessing<1.2,>=1.1.1
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Requirement already satisfied: wheel>=0.26 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (0.34.2)
Processing c:\users\user\appdata\local\pip\cache\wheels\a0\16\9c\5473df82468f958445479c59e784896fa24f4a5fc024b0f501\termcolor-1.1.0-py3-none-any.whl
Collecting astunparse==1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting absl-py>=0.7.0
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Requirement already satisfied: wrapt>=1.11.1 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.11.2)
Requirement already satisfied: numpy<1.19.0,>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.18.5)
Collecting grpcio>=1.8.6
  Using cached grpcio-1.33.2-cp38-cp38-win_amd64.whl (2.7 MB)
Collecting tensorflow-estimator<2.4.0,>=2.3.0
  Using cached tensorflow_estimator-2.3.0-py2.py3-none-any.whl (459 kB)
Requirement already satisfied: six>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.15.0)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting google-pasta>=0.1.8
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting gast==0.3.3
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Collecting tensorboard<3,>=2.3.0
  Using cached tensorboard-2.3.0-py3-none-any.whl (6.8 MB)
Requirement already satisfied: h5py<2.11.0,>=2.10.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from protobuf>=3.9.2->tensorflow) (49.2.0.post20200714)
Requirement already satisfied: requests<3,>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow) (2.24.0)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.23.0-py2.py3-none-any.whl (114 kB)
Requirement already satisfied: werkzeug>=0.11.15 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow) (1.0.1)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.2-py2.py3-none-any.whl (18 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.3-py3-none-any.whl (96 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.7.0-py3-none-any.whl (779 kB)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow) (2.10)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3.5"
  Using cached rsa-4.6-py3-none-any.whl (47 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Installing collected packages: protobuf, keras-preprocessing, termcolor, astunparse, absl-py, grpcio, tensorflow-estimator, opt-einsum, google-pasta, gast, cachetools, pyasn1, pyasn1-modules, rsa, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, markdown, tensorboard-plugin-wit, tensorboard, tensorflow

pip install tensorflow 명령어 치면 이렇게 떠요 Requirement already satisfied면 tensorflow가 이미 있다는 말 아닌가요.. 근데 쥬피터노트북에서 import keras 실행이 안되네요.. 비주얼 프로그램을 깔아봤는데도 안돼요

**Comment by taeseug** [comment]
import tensorflow 하면 되나요
tensorflow 2.0 버젼부터는 keras를  포함하고 있습니다. 

사용시 

from tensorflow.keras.datasets import mnist 
으로 사용하시면 됩니다

**Comment by eun4204** [comment]
쥬피터에 하는거 말씀하신거면 됩니다

**Comment by taeseug** [comment]
tensorflow 2.0 이상 버젼에 맞게 변형된 mnist code 입니다,
압축풀어서 jupyter notebook에서 읽어 드려 실행시켜 보세요
[MNIST실습.zip](https://github.com/keris2020/hackathon/files/5492974/MNIST.zip)
