### ISSUE TITLE
Hello NSML!이 안떠요! 어디가 오류인가요?

### ISSUE THREAD

**Issue by binwon06** [keris2020/hackathon#45]
![캡처](https://user-images.githubusercontent.com/73326204/98194654-379a1400-1f63-11eb-91d6-1a0c75a41b3b.PNG)

Hello NSML!이라고 떠야하는데 오류만 뜹니다 아까도 관련해서 질문드렸는데 이해가 안돼서 다시 질문드립니다!

**Comment by taeseug** [comment]
작성하신 main.py  code 올려 주실수 있나요
