### ISSUE TITLE
선생님께서 알려주신대로 했습니다만...

### ISSUE THREAD

**Issue by ksy809** [keris2020/hackathon#46]
아나콘다도 지우고 파이선도 지우고 재부팅 했습니다. 그리고 아나콘다를 다시 설치하라고해서 다시 설치까지 했습니다. 그리고 아나콘다에서 conda install tensorflow를 입렸습니다. 그러나 그 결과 

(base) C:\Users\User>conda install tensorflow
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - tensorflow -> python[version='3.5.*|3.6.*|3.7.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

(base) C:\Users\User>

이렇게 나옵니다. 뭐가 잘못된 걸까요? 또 다른 해결방안 없을까요? 그리고 한 질문에 세가지 해결방안 말고 정리된 한 가지 해결방만 올려주시면 안될까요? 너무 어렵습니다.

**Comment by Jun-Pyo-Park-PhD** [comment]
pip install tensorflow 로 한번 시도해 보세요.
안되면 상태 체크를 해야할 것 같은데, 오픈카톡방에서 알려주세요.

**Comment by kjn6318** [comment]
학교로 전화드리고 pc 환경 등에 대해 좀 더 자세히 안내드리기로 했습니다. 감사합니다.

**Comment by keris2020** [comment]
잘 해결되서 다행이네요.
본 이슈는 클로징 하겠습니다 :)
