### ISSUE TITLE
주피터 노트북에서 python3 실행 중 import keras 오류

### ISSUE THREAD

**Issue by ilnarago** [keris2020/hackathon#50]
![image](https://user-images.githubusercontent.com/33611146/98236838-53270e00-1fa7-11eb-92c5-cc731412934c.png)

맨 위에 import keras를 입력했는데 이런 오류가 뜹니다.

그대로 진행해도 될까요? 다른 코드들은 정상적으로 진행이 되는 것같은데 맨 위 코드만 저러네요.

**Comment by ilnarago** [comment]
--추가
conda update --all 명령문을 실행해도 같은 결과가 나옵니다.

**Comment by taeseug** [comment]
tensorflow 2.0 이상버젼에서는 keras 가 tensorflow 에 합쳐졌습니다.
따라서 tensorflow 2.0 이상에서는 

from tensorflow.keras.dataset import mnist 
df = mnist.load_data()

로 사용하시면 됩니다.
