### ISSUE TITLE
hello nsml개발 프로그래밍 저장

### ISSUE THREAD

**Issue by nayeon902** [keris2020/hackathon#51]
저장 어떻게 하나요??
주피터노트북에서 하는게맞나요?
![Screenshot_20201106-000843_Gallery](https://user-images.githubusercontent.com/73542475/98258801-a78cb680-1fc4-11eb-873c-74ad078c7218.jpg)

**Comment by Jun-Pyo-Park-PhD** [comment]
주피터에서 프로그래밍 했을 경우
1. 왼쪽 상단 File -> Download as 선택
2.  .py 를 선택해서 main.py 로 저장 (이때 저장 경로는 C:\nsml 로 하시면 됩니다)
3. nsml 터미널로 nsml에 접속해서 실행 (접속 후 main.py 파일이 저장되어 있는 폴더에 가서 실행, 위의 경우면 cd c:\nsml)

실행 명령어는 아래 명령어를 치시고, 세션이 잘 생성되었는지 확인하면 됩니다.
nsml run -e main.py 

결과는 아래주소로 들어가서 nsml 웹에서 확인하면 됩니다.

ai.nsml.navercorp.com/terminal/방금생성된세션이름

예> 세션명이 KERIS019/None/21 인 경우, 인터넷 주소창에 아래처럼 입력
![image](https://user-images.githubusercontent.com/70569284/98259869-fa1aa280-1fc5-11eb-9b5b-5ca0eba02724.png)

**Comment by nayeon902** [comment]
파일이 없다고 뜹니다
![Uploading 20201106_002818.jpg…]()
main.py로 파일명을 바꿔도 실행할수있는프로그램이 아니라고 뜹니다
cd c:\nsml로 접속하는게 밑의 명령어인가요?
그리고 혹시 저장경로는 어떻게바꾸나요??

**Comment by Jun-Pyo-Park-PhD** [comment]
파일이 없다고 뜨는건 3번에서 main.py로 이동하지 않았기 때문인데
위의 이슈에서 설명해드릴게요.

**Comment by kjn6318** [comment]
메모장이나 소스 프로그램에서 아래처럼 입력하고 다른 이름으로 저장을 눌러 main.py 파일을 하나 생성하세요.
그리고 해당 파일을 실행하고자 하는 폴더로 옮겨주면 됩니다.
`print('Hello! KERIS')`

**Comment by nayeon902** [comment]
네 감사합니다. 그런데 주피터노트북에서 저장한파일을 제대로 옮겼는데도 제대로 실행이되고있지않습니다
![20201106_191647](https://user-images.githubusercontent.com/73542475/98354906-bcb92200-2064-11eb-8d18-1a67718c8358.jpg)
