### ISSUE TITLE
명령프롬프트와 cmd에서 nsml run 실행이 안됩니다

### ISSUE THREAD

**Issue by nayeon902** [keris2020/hackathon#52]
김여고 김나연
![20201106_004216](https://user-images.githubusercontent.com/73542475/98262572-208e0d00-1fc9-11eb-80d3-ff6e14f1e9be.jpg)
![20201106_004236](https://user-images.githubusercontent.com/73542475/98262599-25eb5780-1fc9-11eb-939c-610db07a9b1d.jpg)
여기에서 명령프롬프트는 users\owner 로 되어있고 cmd는 윈도우 시스템으로 되어있는데 C드라이브류 바꿀수는 없나요?
이거때문에 계속 main파일이랑 nsml run이 실행이 안되는거 같아서요

**Comment by bluebrush** [comment]
users\owner에서 아래와 같이 디렉토리 하나 생성해서 실행하시면 될 어떨까합니다. 
```
md mydir
cd mydir
copy ../main.py .
copy ../nsml .
nsml run -e main.py
```

**Comment by taeseug** [comment]
c:\windows\system32 디렉토리는 윈도우즈를 동작하게하는 관련 프로그램이 있는 디렉토리입니다. 
여기서 디렉토리를 만들고 테스트를 할경우 시스템이 죽는 경우가 발생할 수 있습니다.

**Comment by kjn6318** [comment]
김나연 학생님, cmd 또는 아나콘다 프롬프트에서 main.py 파일이 있는 경로로 이동해서 명령문을 실행해주세요.

**Comment by nayeon902** [comment]
넵 해결되었습니다 감사합니다
