### ISSUE TITLE
nsml 파일을 C로 옮겼는데 nsml 로그인이 실행이안됩니다

### ISSUE THREAD

**Issue by nayeon902** [keris2020/hackathon#53]
nsml폴더를 c로옮겼는데 환경변수를 다시 어떻게해야될지 모르겠습니다. 그리고 nsml사용법 링크에서 pwd를 입력하라는게 무슨말인지모르겠습니다

**Comment by Jun-Pyo-Park-PhD** [comment]
nsml 폴더라는게 어떤건지 사진 찍어서 보여주세요.

**Comment by nayeon902** [comment]
![20201106_011417](https://user-images.githubusercontent.com/73542475/98266242-6b118880-1fcd-11eb-8801-e67b8eab1d8a.jpg)

**Comment by nayeon902** [comment]
명령프롬프트, cmd 둘다 실행이안됩니다

**Comment by Jun-Pyo-Park-PhD** [comment]
이건 nsml의 경로(Path)가 설정이 안되서 나오는 메시지인데요.

컴퓨터 -> 고급시스템설정 -> 시스템변수에서 Path를 선택하시고 편집 누르셔서
새로 만들기 고르시고 nsml.exe의 경로를 넣어주면 됩니다.

**Comment by Jun-Pyo-Park-PhD** [comment]
경로는 c:\nsml 이라고 넣어봐주세요.

**Comment by nayeon902** [comment]
경로를 어떻게넣나요?
그리고 환경변수를 path로 해놓아도 계속 다른걸로 되돌아가는데 원래이런건가요?

**Comment by nayeon902** [comment]
![20201106_011949](https://user-images.githubusercontent.com/73542475/98266926-2f2af300-1fce-11eb-90c3-ade50fd517aa.jpg)
여기 이미 넣어놨는데도 실행이 안됩니다

**Comment by Jun-Pyo-Park-PhD** [comment]
cmd 창 한번 띄우셔서 

1) cd c:\nsml 입력

2) nsml login 입력 해서 되는지 확인

**Comment by nayeon902** [comment]
됩니다! 그럼 저거 다 된건가요?

**Comment by Jun-Pyo-Park-PhD** [comment]
아래처럼 해보세요

1. cd c:\ 입력

2. nsml login 입력

안되면 Path가 설정이 안된거에요

**Comment by nayeon902** [comment]
실행 됩니다! 감사합니다

**Comment by Jun-Pyo-Park-PhD** [comment]
다행이네요 :)

커맨드창에서 nsml run 하실 경우엔 실행하는 파일 (이번 경우엔 main.py)와 항상 같은 경로에 있어야 합니다.

커맨드창
c:\nsml>nsml run -e main.py   <- 맞음 
c:\>nsml run -e main.py <- 틀림 (main.py 파일은 c:\nsml 폴더에 있기 때문에 동작하지 않음)
