### ISSUE TITLE
데이터 학습에서 오류가생깁니다

### ISSUE THREAD

**Issue by nayeon902** [keris2020/hackathon#54]
데이터학습을하려고했는데 학습이 안됩니다.
![20201106_030312](https://user-images.githubusercontent.com/73542475/98279073-d151d780-1fdc-11eb-94fc-282f52ceade9.jpg)

**Comment by taeseug** [comment]
nsml  run 을 실행시킨 디렉토리에 .으로  시작되는 디렉토리가 있어 나는에러입니다   위의 로그에 의하면 AI_Starton2019-main￦￦.github 로 인해발생한 에러입니다.  
AI_Starton2019-main  밑에 있는   16_tcls_movie  directory 에서 실행시켜보세요

![image](https://user-images.githubusercontent.com/34451432/98283975-c77fa280-1fe3-11eb-93c8-a9cd7d00abda.png)

**Comment by nayeon902** [comment]
아나콘다 프롬프트에서 실행시켜야되는건가요?
혹시 C:₩Users₩owner 를 C:₩Users₩MSI₩test₩AI_Starthon_2019로 어떻게 바꾸나요?

**Comment by nayeon902** [comment]
위에 문제는 해결되었는데 파일이 실행이 안됩니다
![20201106_040443](https://user-images.githubusercontent.com/73542475/98285014-488b6980-1fe5-11eb-84bf-376b4e62eb2e.jpg)
그리고 C드라이브 볼륨에 이름이 없다고 뜹니다

**Comment by Jun-Pyo-Park-PhD** [comment]
nsml run 을 cmd 창에서 실행하세요.

**Comment by taeseug** [comment]
nsml 설치된 디렉토리 경로를 컴퓨터 환경 변수에 설정하지 않아서 경로를 못찾는 경우 입니다

 nsml의 경로(Path)가 시스템 환경 변수 설정이 안되서 나오는 메시지인데요.
방법은 2가지가 있습니다.  2번째 방법은 nsml 실행시 nsml.exe 파일이 있는 경로를 계속 적어주어야 하는 불편함이 있습니다

방법 1. 
컴퓨터 -> 고급시스템설정 -> 시스템변수에서 Path를 선택하시고 편집 누르셔서
새로 만들기 고르시고 nsml.exe의 경로를 넣어주세요  참고 문서는 
 NSML 및 해커톤 가이드 http://gg.gg/mapo_ai_doc 에 있는   NSML 개발 환경 구성 부분을 참조하여 진행 하시면 됩니다.

방법2 
16_tcls_movie_small 디렉토리에서 nsml.exe가 있는 디렉토리를 다써주는 방법입니다 
c:\nsml\nsml.exe -d 16_tcls_movie_small  -e main.py
![image](https://user-images.githubusercontent.com/34451432/98312106-54425480-2014-11eb-85ca-34d4c53ee434.png)
