### ISSUE TITLE
세션이 안뜨는데 뭐가 잘못된걸까요?

### ISSUE THREAD

**Issue by nayeon902** [keris2020/hackathon#55]
16_tcls_movie_small 파일을 열었는데 세션명이 안보입니다
![20201106_042043](https://user-images.githubusercontent.com/73542475/98286650-a751e280-1fe7-11eb-821a-7b17c49b8296.jpg)

**Comment by bluebrush** [comment]
-d 옵션의 앞에 space가 있어야하며, -e 옵션 앞에도 space가 있어야합니다. 
```
nsml run -d [dataset] -e [entry-point.py] 
```

**Comment by kjn6318** [comment]
그리고 간단하게 본인의 세션만 확인하시려면 main.py가 있는 경로 위치에서 다음 명령을 실행하시면 됩니다.
`nsml run`

**Comment by taeseug** [comment]
session은  nsml run -d 16_tcls_movie_small -e main.py 가 정상적으로 실행 되면 로그끝부분에  보여줍니다. 
![image](https://user-images.githubusercontent.com/34451432/98311552-04af5900-2013-11eb-9c21-42371fa3ecae.png)
