### ISSUE TITLE
데이터 학습(학습 실행시) 오류

### ISSUE THREAD

**Issue by flyinggw** [keris2020/hackathon#58]
![qqq](https://user-images.githubusercontent.com/73579934/98320083-7b555200-2025-11eb-8808-18eac4a1bf1c.png)
![qq2](https://user-images.githubusercontent.com/73579934/98320316-046c8900-2026-11eb-9a49-30b0d57f7853.png)

안녕하세요.
데이터 학습(학습 실행)시 첨부파일과 같은 오류?가 발생하고, 학습이 진행되지 않네요.
nsml run -d 16_tcls_movie_small -e main.py
명령어로 실행해본 화면이고,
c:\nsml\AI_Starthon_2019\에 16_tcls_movie 폴더와 sampledata 폴더만 둔 상태입니다.

**Comment by Jun-Pyo-Park-PhD** [comment]
dataset path를 못찾는 듯 하네요.

혹시 실행시킨 경로에 main.py 파일만 있지 않은가요?

**Comment by Jun-Pyo-Park-PhD** [comment]
경로 잘 확인하시고 전체 베이스라인 파일이 있는 경로에서 실행시켜보세요 :)

**Comment by taeseug** [comment]
기본 가이드인 http://gg.gg/mapo_ai_doc  파일에 있는  " 영화 평점 리뷰로 따라하기: 데이터셋 다운로드 " 따라 실행 해 보세요  위에러는 필요없는 파일들이 같이 읽어 들여서 발생하는 문제인것
같습니다

가이드에 따르면  " 데이터셋 파일을 모두 받으셨다면 AI_Starthon_2019 폴더에서 16_tcls_movie 폴더 외에는 모두 삭제해주세요" 라는 부분이 있습니다.

**Comment by flyinggw** [comment]
> 더 외에는 모두 삭제해주세요" 라는 부분이 있습니다.

저 링크 보고 했고, 폴더내에서 해당 폴더외에는 삭제하고 한 상태이긴 합니다...

**Comment by flyinggw** [comment]
> 경로 잘 확인하시고 전체 베이스라인 파일이 있는 경로에서 실행시켜보세요 :)

nsml 폴더내에는 main.py(16_tcls_movie 폴더에서 복사한 파일), nsml.exe 파일, AI_Starton_2019 가 있고
AI_Starton_2019 폴더 내에는 16_tcls_movie 폴더만.
16_tcls_movie 폴더 내에는 기존에 들어있던 파일들.
있는 상태로 했는데 문제 있을까요?

**Comment by taeseug** [comment]
실행시키실때는 16_tcls_movie  디렉토리에 들어가서 실행시켜야 됩니다

**Comment by flyinggw** [comment]
답변 감사합니다 해결했습니다
