### ISSUE TITLE
session_no와 checkpoint

### ISSUE THREAD

**Issue by jsh0726** [keris2020/hackathon#60]
4번 영화 평점에서 (2) 학습 완료된 모델 확인  안에 session_no와 checkpoint는 어떻게 확인하나요?

**Comment by taeseug** [comment]
1. session -id 는 nsml run 하시면 끝부분에 표시됩니다
![image](https://user-images.githubusercontent.com/34451432/98355162-220d1300-2065-11eb-9e19-bf402d9af19e.png)

2. 확인한 session-id를 이용해  nsml model ls  session-id 하시면 model과 check point를 확인하실 수 있습니다.
![image](https://user-images.githubusercontent.com/34451432/98355442-7912e800-2065-11eb-94f9-44ace1470aaf.png)
