### ISSUE TITLE
nsml 세션에 올라간 모델 관련 질문

### ISSUE THREAD

**Issue by ghost** [keris2020/hackathon#61]
1. 학습이 완료된 모델을 재학습시키는 방법이 어떻게 되나요?
2. 학습이 완료된 모델을 로컬 파일로 다운받아서 저장하는 방법이 있나요?
3. 모델이 올라가는 서버 용량에 제한이 있나요?

**Comment by taeseug** [comment]
1) 재학습은 가능하지만 기간이나 운영 여건상 해커톤 대회에서는 제한하고 있습니다. 
2) 모델이름 확인하고
nsml model pull sessionid modelname 저장위치
3) 용량 제한은 300mb라고 이미 공지된 것 같습니다.

**Comment by ghost** [comment]
친절한 답변 감사합니다.
