### ISSUE TITLE
nsml run 이 안돼요 ㅠㅠ

### ISSUE THREAD

**Issue by MJ-u** [keris2020/hackathon#63]
nsml 폴더 안에 16_tcls_movie 넣고 main.py가 있는것을 확인하고서 nsml run을 하려했는데 안돼요 ㅠㅠ
이동 경로를 바꿔서 했는데도 안되는 것 같아요..
![20201107_010555](https://user-images.githubusercontent.com/73641391/98387960-70d2a100-2095-11eb-832c-09998c26357d.jpg)

**Comment by taeseug** [comment]
nsml.exe 가 있는 경로가 환경변수에 설정이 안되서 실행이 안된 경우 입니다. 

아래  "**[공지]NSML 터미널 설치 후 환경변수 경로 설정 방법 및 nsml run 명령어 실행 방법 안내**"#59 을 참조하여 환경변수를 설정한 후 16_tcls_movie 디렉토리에서 nsml run -d 16_tcls_movie_small -e main.py   을 실행합니다.

**Comment by kjn6318** [comment]
윈도우즈 컴이니 http://gg.gg/mapo_ai_doc 여기 가이드 문서에서 환경변수라고 검색하면 나오는 방법을 따라해 주세요. 윈도우 고급 시스템 설정에서 (c:￦nsml￦...)로 시작하는 경로를 Path에 추가해주셔야 합니다.

**Comment by MJ-u** [comment]
환경변수에  경로 추가하고 가이드에 나오는 명령어들 입력해봤는데 안돼요..ㅠㅠ
![SmartSelectImage_2020-11-07-10-50-03](https://user-images.githubusercontent.com/73641391/98428934-224df280-20e7-11eb-915e-d59f1a120334.png)

**Comment by MJ-u** [comment]
@kjn6318
