### ISSUE TITLE
nsml model ls에서 loss값이 이거맞나요?

### ISSUE THREAD

**Issue by nayeon902** [keris2020/hackathon#64]
![20201107_010935](https://user-images.githubusercontent.com/73542475/98388419-1554e300-2096-11eb-8c4e-ef6b61c1e2b2.jpg)
이쪽줄에 있는게 모두 loss값이 맞나요??

**Comment by taeseug** [comment]
네 맞습니다 앞에 1.도 포함해서입니다  1.43951386  입니다
![image](https://user-images.githubusercontent.com/34451432/98423435-ed837080-20d1-11eb-9dec-aaa6cea7a994.png)
