### ISSUE TITLE
세션이 새로 돌아가면, 왜 숫자가 연속적이지 않게 만들어지나요?

### ISSUE THREAD

**Issue by ghost** [keris2020/hackathon#66]
1. 세션이 새로 돌아가면, 왜 숫자가 연속적이지 않게 만들어지나요? 예)31, 33 등; 중간에 삭제하지는 않았습니다.
2. 세션이 돌아가면 숫자 말고 이름으로 저장하는방법이 있나요?

**Comment by bluebrush** [comment]
@gwangdeok01 님. submit 등의 세션도 숫자가 증가하게 됩니다(실제는 보이지 않음). 그래서 중간중간 빠질 수 있습니다.
