### ISSUE TITLE
AdamP 사용 불가 문제

### ISSUE THREAD

**Issue by osyori** [keris2020/hackathon#67]
현재는 최적화 함수가 Adam 으로 적용되어 있지만 AdamP를 추천해주셔서 AdamP로 바꾸고 nsml에서 실행시켜보았으나 AdamP 라는 module이 없다고 나옵니다. local에서는 설치를 하였는데, 무엇이 문제일까요?

**Comment by SieR-VR** [comment]
setup.py에 adamp를 추가해야합니다.

from distutils.core import setup
setup(
    name='nsml movie review',
    version='1.0',
    description='',
    install_requires=[
        'adamp'
    ]
)
