### ISSUE TITLE
NSML 터미널 로그인 실패... 그 전까지 잘됐었음.

### ISSUE THREAD

**Issue by gonsTM** [keris2020/hackathon#7]
nsml 터미널 로그인 시도시 아래와 같은 문구가 뜨는데... 깃헙 ID랑 비번은 정상적으로 입력했습니다.(그전에 로그인도 됐었고요.)
근데 갑자기 저녁 먹고 왔는데... 아래 문구가 뜨네요?
login failed: Authentication failure. Please login again.

한번 더 시도해봤더니 문구가 아래와 같이 바뀌었습니다.
login failed: You are not a registered user

혹시 5번 이상 시도해서 계정이 잠김 상태가 되었다는 건가요?

**Comment by Jun-Pyo-Park-PhD** [comment]
클라이언트 접속 장애가 있었습니다.
현재 정상화되었습니다. 불편을 드려 죄송합니다.
