### ISSUE TITLE
사용가능 gpu, cpu 질문

### ISSUE THREAD

**Issue by ghost** [keris2020/hackathon#73]
1. nsml에서 최대로 할당받을 수 있는 gpu, cpu 개수와 용량은 어떻게 되나요?
2. nsml 홈페이지에서 resources에 가면 있는 gpu, cpu 수는 어떤걸 의미하나요?

**Comment by taeseug** [comment]
1. [공지] 대회 규칙, 자원 쿼터, 최종 순위 #4 에 보시면 팀당 할당된 리소스는  1GPU, 4CPU, 28GB RAM, (GPU는 P40으로 VRAM 24G씩) 입니다

2. 현재 할당되어 있는 전체 리소스에 대한 설명입니다. 현재 할당되여 사용하는 GPU 모델은 P40 며 total  52개가 할당되어 있으며 
    현재 몇개의 GPU가 사용 되고 있는지를 알려줍니다.
