### ISSUE TITLE
요기서 뭐가 오류인건지 잘모르겠어요

### ISSUE THREAD

**Issue by route4421** [keris2020/hackathon#74]
![image](https://user-images.githubusercontent.com/73597810/98553166-ac15df80-22e2-11eb-86d6-653f03ada3e8.png)

**Comment by taeseug** [comment]
reshape  이 오타가난것으로 보입니다  오타로 인해 모듈이 없다고 나오는  에러입니다 reshpae 을 reshape으로 변경해주세요  
![SmartSelect_20201110-071430_KakaoTalk](https://user-images.githubusercontent.com/34451432/98602941-945f4b00-2324-11eb-975e-e8901d583fc9.jpg)
