### ISSUE TITLE
GPU.avg 질문

### ISSUE THREAD

**Issue by rlawoons34** [keris2020/hackathon#75]
![캡처](https://user-images.githubusercontent.com/73623082/98573357-21d97580-22fa-11eb-8391-a065870293f5.PNG)

제가 유추한바로는 아마 이미종료된 세션에도 gpu가 할당되는것 같은데,정확히 무슨 현상인지 잘몰라 질문드립니다.
위사진처럼 이미 종료된 세션에서도 왜 저런 이모티콘(화난 사진,gpu할당 몇 퍼센트)이 붙는 이유가 무엇이며,해결방법이 무엇인지 궁금합니다.(저게 그 좀비세션?인가 하는건가요?)

**Comment by SieR-VR** [comment]
이미 종료된 세션에는 GPU가 할당되지 않는걸로 압니다.
저렇게 화난 이모티콘이 붙는 이유는 사용된 GPU%가 너무 낮았기 때문인것 같습니다.

**Comment by rlawoons34** [comment]
> 이미 종료된 세션에는 GPU가 할당되지 않는걸로 압니다.
> 저렇게 화난 이모티콘이 붙는 이유는 사용된 GPU%가 너무 낮았기 때문인것 같습니다.

아 그렇군요.그럼 너무 단순한 모델로 학습을 시켜서 그런것인가요?or epoch값이 너무 낮아서 그런것인가요? baseline hyperparameter값을 계속 조정함에도 불구하고 계속 저 이모티콘이 붙습니다.movie challenge에서는 이런 문제가 발생하지 않아 혹 애초에 주최측에서 단순히 parameter값을 변경하는것이 아니라,보다 복잡도를 올릴려는 의도를 가지고 있는것인지.....다시한번 답변 감사합니다!
