### ISSUE TITLE
에러가 뜹니다!

### ISSUE THREAD

**Issue by jsh0726** [keris2020/hackathon#78]
[
![image](https://user-images.githubusercontent.com/73572724/98653611-948d3400-2380-11eb-9c75-3af94b197367.png)
](url)

**Comment by bluebrush** [comment]
@Jeonsohee1122 님, 전체 자원에 여유가 있어서 쿼터를 상향 하였습니다. 다시 시도해보시기 바랍니다. 
현재 적용 중인 쿼터는 GPU:2개, CPU:8개, RAM: 56GB 입니다. `nsml run`에서 별도 옵션이 없으면, 기본으로 1GPU, 2CPU, 24GB RAM으로 시작하니 참고부탁드립니다.

**Comment by taeseug** [comment]
쿼터를 gpu/cpu/ram 2 8 56 으로 변경되었습니다  다시한번 실행보세요

**Comment by jsh0726** [comment]
감사합니당
