### ISSUE TITLE
nsml 로그인 실패

### ISSUE THREAD

**Issue by gwangdeok03** [keris2020/hackathon#8]
깃허브 유저 이름과 비밀번호를 맞게 입력하였는데도 오류가 나서 질문드립니다.
![캡처](https://user-images.githubusercontent.com/73578373/97865677-eb29bb00-1d4d-11eb-8efb-4a4e318521aa.PNG)

**Comment by Jun-Pyo-Park-PhD** [comment]
Authentication Failure는 비밀번호가 틀린 경우 출력되는 메시지입니다. 비밀번호 확인 후 로그인 부탁드립니다.

**Comment by gwangdeok03** [comment]
깃허브를 다시 로그인 해봤을 때 이 비밀번호가 맞는데 nsml 터미널에 로그인이 되지 않습니다. 이럴 땐 어떻게 해야 하나요?

**Comment by Jun-Pyo-Park-PhD** [comment]
클라이언트 접속 장애가 있었습니다.
현재 정상화되었습니다. 불편을 드려 죄송합니다.
