### ISSUE TITLE
터미널 로그인 오류

### ISSUE THREAD

**Issue by jwchae45** [keris2020/hackathon#9]
터미널에서 `nsml login` 명령어로 로그인을 시도했으나 "login failed: Authentication failure. Please login again." 메시지가 뜨면서 실패합니다. 깃허브 Username은 jwchae0405이며, 비밀번호까지 정상적으로 입력했으나 로그인이 되지 않는데 어떻게 해결할 수 있을까요?

**Comment by Jun-Pyo-Park-PhD** [comment]
해당 아이디는 정상 등록되어 있습니다. Authentication failure는 비밀번호 오류인듯 한데, 
혹시 웹버전 NSML에서 로그인되는지 확인 부탁드립니다.
![image](https://user-images.githubusercontent.com/70569284/97865845-317f1a00-1d4e-11eb-8bf0-e4cf2f0070a4.png)

**Comment by jwchae45** [comment]
웹버전 NSML에서는 정상적으로 로그인되나 터미널에서는 잘 되지 않습니다. 현재 다른 팀원들도 웹 버전에는 GItHub 계정으로 정상적으로 로그인 되나 터미널에서 위와 같은 문제가 발생합니다.

**Comment by jwchae45** [comment]
![image](https://user-images.githubusercontent.com/73330038/97867357-0cd87180-1d51-11eb-9e20-449a738f05c1.png)

**Comment by Jun-Pyo-Park-PhD** [comment]
클라이언트 접속 장애가 있었습니다.
현재 정상화되었습니다. 불편을 드려 죄송합니다.
