### ISSUE TITLE
[bug] Interrupted by user

### ISSUE THREAD

**Issue by gunyu1019** [keris2020/hackathon#93]
제가 실수로 submit 도중에 컨트롤 + C키를 눌렀습니다. 그런데, 정작 세션은 정지되어도 CPU와 GPU가 그대로 사용 중입니다. 
![Screenshot_20201113-015400_Gallery](https://user-images.githubusercontent.com/16767890/98970314-2187e700-2553-11eb-9dcb-7a899798aa82.jpg)

**Comment by bluebrush** [comment]
@gunyu1019 님, 해당 submit session을 삭제하였습니다. 다시 시도하시면 될 것 같습니다.
